# Port dynamique requis par la plateforme
server.port=${PORT:8081}

# Connexion a Neon Database
spring.datasource.url=jdbc:postgresql://ep-tiny-hill-aen6kxvt-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_0ZmNKrOaBdI1
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecte PostgreSQL et validation du schema
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Limite de taille pour les fichiers
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
spring.jpa.hibernate.ddl-auto=update