# Port dynamique requis par Koyeb
server.port=${PORT:8081}

# Connexion à Neon (Remplacez VOTRE_MOT_DE_PASSE par celui de Neon)
spring.datasource.url=jdbc:postgresql://ep-tiny-hill-aen6kxvt-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_0ZmNKrOaBdI1
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecte PostgreSQL et validation du schéma
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# "validate" ou "none" pour conserver les données déjà importées sur Neon
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# Augmenter la limite pour un seul fichier (ex: 10 Mo)
spring.servlet.multipart.max-file-size=10MB

# Augmenter la limite globale de la requÃªte avec plusieurs fichiers (ex: 50 Mo)
spring.servlet.multipart.max-request-size=50MB